name: Continuous Integration with Github Actions

on:
  push:
    branches: 
      - main 

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
    - name: Analisar o Código
      uses: actions/checkout@v3